def get_via_pl(d,pl):
def set_via_pl(d,pl,v):
def set_dflt_via_pl(d,pl,*args):
def del_via_pl(d,pl):
def is_leaf_pl_via_dict(d,pl):
def get_type_str(o):
def get_kschema(d):
def get_kstruct(d):
def get_ppl(pl):
def get_plmat(d):
def get_wfs_pl(d):
def get_sdfs_pl(d):
def get_sdfs_leaf_pl(d):
def get_sdfs_nonleaf_pl(d):
def plsdfs_to_kstruct(sdfs):
def is_leaf_pl_via_plsdfs(sdfs_pl,pl):
def get_pl_children_via_plsdfs(plsdfs,pl):
def get_vfstch(d):
def get_vlstch(d):
def get_which_vchild(d,which):
def get_some_vchildren(d,*whiches):
def get_vchildren(d):
def get_vchild_count(d):
def is_leafv(d):
def get_wfs_vmat(d):
def get_wfs_vlist(d):
def get_sdfs_vlist(d):
def get_sdfs_leaf_vlist(d):
def get_vstruct(d):
def get_count(d):
def flatten_to_leaf_entries(d):
def flatten_to_leaf_dict(d):
def deflatten_from_leaf_entries(leaf_entries):
def get_flatvl_via_kstruct(d,kstruct):
def unzip(d):
def zip(kstruct,flat_vl):
def _get_mat(d):
def _is_leaf_ele(ele):
def _get_wfs_elist(d):
def _get_eparent(ele):
def _get_efstch(ele):
def _get_ersib(ele):
def _get_ersib_of_fst_ance_having_rsib(ele):
def _get_ele_sdfs_next(ele):
def _get_ele_sdfs(ele):

